version: "3.9"

services:
  abbit-db:
    image: postgres:15-alpine
    container_name: abbit-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abbit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    environment:
      - TZ=Europe/Vienna
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: applicant-api
    environment:
      - NODE_ENV=production
      - CAMUNDA_URL=http://camunda:8080/engine-rest
      - CAMUNDA_REG_PROCESS_KEY=student_registration
      - DATABASE_URL=postgresql://postgres:postgres@abbit-db:5432/abbit?schema=public
    depends_on:
      - camunda
      - abbit-db
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    container_name: applicant-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data:
