version: "3.9"

services:
  abbit-db:
    image: postgres:15-alpine
    container_name: abbit-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abbit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    environment:
      - TZ=Europe/Vienna
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: abbit-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: applicant-api
    environment:
      - NODE_ENV=production
      - CAMUNDA_URL=http://camunda:8080/engine-rest
      - CAMUNDA_REG_PROCESS_KEY=student_registration
      - DATABASE_URL=postgresql://postgres:postgres@abbit-db:5432/abbit?schema=public
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=abbit-files
    depends_on:
      - camunda
      - abbit-db
      - minio
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    container_name: applicant-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  minio_data:
