services:
  api:
    command: npm run start:dev
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./apps/api/tsconfig.json:/app/apps/api/tsconfig.json

  web:
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
